version: '3.4'
services:
  prometheus:
    restart: unless-stopped
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - 9190:9090
    volumes:
      - ./config:/etc/prometheus
    environment:
      - TZ=Asia/Shanghai
    privileged: true
