version: '3'
services:
  nginx:
    restart: always
    container_name: sdnn-doc
    image: nginx
    ports:
      - 9090:80
    volumes:
      - /workspace/share/sdnn_doc:/usr/share/nginx/html
      #- /usr/local/nginx/html:/usr/share/nginx/html
      #- /usr/local/nginx/www:/var/www
      #- /usr/local/nginx/logs:/var/log/nginx
      # 有可能会出现不能挂载，这个时候用手动拷贝配置文件就行
      #- /workspace/guohua.zhu/web/nginx/nginx.conf/:/etc/nginx/nginx.conf
      #- /usr/local/nginx/etc/cert:/etc/nginx/cert
      #- /usr/local/nginx/conf.d:/etc/nginx/conf.d
    environment:
      - NGINX_PORT=80
      - TZ=Asia/Shanghai
    privileged: true
