scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9190']
  # 采集node exporter监控数据
  - job_name: 'node'
    static_configs:
      - targets: ['192.168.104.217:9100']
