version: '3'
services:
  nginx:
    restart: always
    container_name: files-server
    image: nginx
    ports:
      - 8090:80
    volumes:
      - /workspace/share/html_download/:/usr/share/nginx/files
        #- /usr/local/nginx/html:/usr/share/nginx/html
        #- /usr/local/nginx/www:/var/www
        #- /usr/local/nginx/logs:/var/log/nginx
      # 有可能会出现不能挂载，这个时候用手动拷贝配置文件就行
      - ./config/nginx.conf/:/etc/nginx/nginx.conf
        #- /usr/local/nginx/etc/cert:/etc/nginx/cert
        #- /usr/local/nginx/conf.d:/etc/nginx/conf.d
    environment:
      - NGINX_PORT=80
      - TZ=Asia/Shanghai
    privileged: true
