version: "3.3"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
        - 11434:11434
    volumes:
      - ollama:/root/.ollama
    networks:
      - ollama-net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  ollama-net:
    driver: bridge
    ipam:
      driver: "default"
      config:
        - subnet: 172.27.0.0/16
          gateway: 172.27.0.1

volumes:
  ollama:
