---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Support System:
    - Semidrive:
        - abbr: SD
          href: https://support.semidrive.com/

    - ARM:
        - icon: si-arm-#0091BD
          href: https://support.armchina.com/servicedesk/customer/user/requests?status=open

