---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Code:
    - Gerrit:
        icon: si-git-#F05032
        href: http://gerrit.semidrive.net:8081/
        description: semidrive code repository
        ping: http://gerrit.semidrive.net:8081/

    - Grok:
        icon: si-ngrok-#1F1E37
        href: http://sh-opengrok.semidrive.cc:8080/source/
        description: semidrive code review
        ping: http://sh-opengrok.semidrive.cc:8080/source/

- SDNN:
    - Benchmark:
        icon: si-plotly-#3F4F75
        href: http://192.168.200.251:8501
        description: neural networks model benchmark and accuracy auto evaluation framework
    - Database:
        icon: si-mongodb-#47A248
        href: http://192.168.200.251:8081
        description: database for store and query benchmark and accuracy data

- Docs:
    - SDNN:
        icon: si-onnx-#005CED
        href: http://192.168.200.251:9090/
        description: document for sdnn software stack
        ping: http://192.168.200.251:9090/

    - CVEngine:
        icon: si-opencv-#5C3EE8
        href: http://10.18.200.24:8088/CN/
        description: document for sdcv module
        ping: http://10.18.200.24:8088/CN/

- Files:
    - Tools:
        icon: si-retool-#3D3D3D
        href: http://192.168.200.251:8090/
        description: Public sdnn tools and toolchain
    - ModelZoo:
        icon: si-zorin-#15A6F0
        href: http://192.168.200.251:8092/
        description: Public Model Zoo

- AI Tools:
    - Xinference:
        icon: si-xdotorg-#F28834
        href: http://192.168.200.251:9997/ui/#/launch_model/custom/llm
        description: Xorbits Inference(Xinference) is a powerful and versatile library designed to serve language, speech recognition, and multimodal models.
    - Dify:
        icon: si-d-#13ADC7
        href: http://192.168.200.251/apps
        description: Dify is an open-source LLM app development platform. Its intuitive interface combines AI workflow, RAG pipeline, agent capabilities, model management, observability features and more, letting you quickly go from prototype to production.
    - SDNN Assistant:
        icon: si-googleassistant-#4285F4
        href: http://192.168.200.251/chat/KUN8YlYs5IFTUM4x
        description: sdnn doc and question assistant

- Server:
    #- Gitlab:
    #    icon: gitlab.png
    #    href: http://192.168.200.251:8929/
    #    description: for sdnn code ci test server and code review
    #    ping: http://192.168.200.251:8929/
    #    server: sdnn-docker
    #    container: gitlab

    - Harbor:
        icon: harbor.png
        href: http://192.168.200.251:9080/
        description: docker image manage server
        ping: http://192.168.200.251:9080/
        server: sdnn-docker
        container: nginx

- Manage:
    - Portainer:
        icon: portainer.png
        href: http://192.168.200.251:9000/
        description: docker manage server
        showStats: true
        server: sdnn-docker
        container: portainer
        widget:
            type: portainer
            url: http://192.168.200.251:9000
            env: 2
            key: ptr_QT/701QirumrvyTR+RoZrhB+MCUgRYqrJYQ6C0DqzUU=

