---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- greeting:
    text_size: xl
    text: SDNN

- resources:
    cpu: true
    memory: true
    cputemp: true
    uptime: true
    refresh: 3000 # optional, in ms
    disk: /

- search:
    provider: google
    focus: true
    showSearchSuggestions: true
    target: _blank

- openmeteo:
    label: 浦东新区
    latitude: 31.24
    longitude: 121.5009
    timezone: Asia/Tokyo
    units: metric # or imperial
    cache: 5 # Time in minutes to cache API responses, to stay within limits

- datetime:
    text_size: xl
    format:
      dateStyle: short
      timeStyle: short
      hour12: true
